name: Release

on:
  release:
    types:
      - released

jobs:
  release:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]
      fail-fast: false
    steps:
      - name: Checking out Git
        uses: actions/checkout@v2
      - name: Setting up Node JS and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: yarn

      - name: 🔨 Installing dependencies
        run: yarn install

      - name: 🔨 Building app
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📤 Publishing ${{matrix.os}} app
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.zip
            dist/*.dmg
            dist/*.exe
            dist/*.yml
